# Generated by Django 3.1.2 on 2020-10-24 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative_regions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrativeregion',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
