# Generated by Django 3.1.2 on 2020-10-30 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filials.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cities', '0002_auto_20201025_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('actual_address', models.CharField(max_length=255)),
                ('legal_address', models.CharField(max_length=255)),
                ('coordinates', models.CharField(max_length=100, validators=[filials.validators.validate_coordinates])),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities.city')),
                ('contact_persons', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
