# Generated by Django 3.1.2 on 2020-10-24 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('filials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filial',
            name='contact_persons',
            field=models.ManyToManyField(to='accounts.Profile'),
        ),
    ]
