# Generated by Django 3.1.2 on 2020-10-25 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
        ('micro_regions', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='microregion',
            unique_together={('name', 'city')},
        ),
        migrations.RemoveField(
            model_name='microregion',
            name='region',
        ),
    ]
