# Generated by Django 3.1.2 on 2020-10-24 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201024_1915'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('code',)},
        ),
        migrations.AddField(
            model_name='profile',
            name='access_level',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Super Admin', 'Super Admin'), ('User', 'User')], default='User', max_length=100),
        ),
    ]
