# Generated by Django 3.1.2 on 2020-10-24 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201024_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='access_level',
            field=models.CharField(choices=[('Администратор', 'Администратор'), ('Супер Администратор', 'Супер Администратор'), ('Пользователь', 'Пользователь')], default='Пользователь', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(choices=[('Менеджер', 'Менеджер'), ('Backend-Developer', 'Backend-Developer'), ('Frontend-Developer', 'Frontend-Developer'), ('Fullstack-Developer', 'Fullstack-Developer')], default='Менеджер', max_length=255),
        ),
    ]
