# Generated by Django 3.1.2 on 2020-10-25 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201024_2151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='access_level',
            new_name='level',
        ),
    ]
