# Generated by Django 3.1.2 on 2020-10-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20201025_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='code',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
